// AUTO-GENERATED FILE — DO NOT EDIT.
//
// OpenAPI types for the Translatarr API, rendered from
// clients/typescript/openapi.json (dumped from the server's Zod schemas in app/lib).
// Regenerate with: clients/typescript/scripts/regenerate.sh
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate text (not persisted)
         * @description Returns ranked translation options, per-option glossary, romanization, and a back-translation. Pass `chatId` to borrow that chat's recent turns as disambiguation context; the result is not stored.
         */
        post: operations["translate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's chats */
        get: operations["listChats"];
        put?: never;
        /** Create a chat */
        post: operations["createChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        /** Fetch a chat with its turns */
        get: operations["getChat"];
        put?: never;
        post?: never;
        /** Delete a chat */
        delete: operations["deleteChat"];
        options?: never;
        head?: never;
        /** Clear turns or rename a chat */
        patch: operations["updateChat"];
        trace?: never;
    };
    "/api/chats/{chatId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate and persist a turn
         * @description Translates `text` and appends it to the chat. Supply `result` (a prior translation of this exact text and language pair) to persist it without a second LLM call.
         */
        post: operations["createTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chatId}/turns/{turnId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
                turnId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Select an option, retranslate, or switch branch */
        patch: operations["updateTurn"];
        trace?: never;
    };
    "/api/speech/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe audio to text
         * @description Requires a configured speech provider. Audio ≤ 15 MB.
         */
        post: operations["transcribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/speech/synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize speech from text
         * @description Requires a configured speech provider. Returns streamed MP3 audio.
         */
        post: operations["synthesize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's API keys */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Mint an API key
         * @description The plaintext `token` is returned only here, once.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            /** @description Provider error code, when applicable. */
            code?: string;
        };
        Ok: {
            /** @constant */
            ok: true;
        };
        /**
         * @description A supported language code, or "auto" for source detection.
         * @enum {string}
         */
        LanguageCode: "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi" | "auto";
        TranslationResponse: {
            /** @description Code of the language the input text is actually written in (e.g. "en", "zh"). */
            detectedSourceLanguage: string;
            /** @description Confidence in the language detection, from 0 to 1. */
            confidence: number;
            /** @description 2-3 natural translation options, ranked best-first. */
            translations: {
                /** @description The translation itself, in the output language. */
                text: string;
                /** @description Romanization of text when it is written in a non-Latin script (pinyin, romaji, etc.); otherwise null. */
                romanization: string | null;
                /** @description Back-translation of text into the source language so the user can verify the meaning. */
                sourceEquivalent: string;
                /** @description Formality of this option's phrasing: formal, polite, neutral, casual, intimate, or vulgar/slang, with the language's native politeness or speech-level term in parentheses when one exists. Casual means relaxed but clean; phrasing with profanity or crude/sexual vocabulary is vulgar/slang; sexually familiar talk between partners is intimate. */
                register?: string;
                /** @description Attitude or emotional coloring of this option's phrasing — a separate axis from register's formality. Prefer one of: playful, teasing, mocking, affectionate, flirtatious, sarcastic, angry, urgent, somber, excited; coin a more precise single word when none fits. Omit entirely when the phrasing is emotionally neutral. */
                tone?: string;
                /**
                 * @description Complete glossary for this option, in source order: every meaningful word or phrase of the source text mapped to its counterpart in this option (omit only pure function words).
                 * @default []
                 */
                keyWords: {
                    /** @description A meaningful word or phrase exactly as it appears in the source text. */
                    source: string;
                    /** @description Its counterpart in this specific translation option. */
                    target: string;
                    /** @description Romanization of target when it is written in a non-Latin script; otherwise null. */
                    romanization: string | null;
                }[];
            }[];
            /**
             * @description Legacy shared glossary; always return an empty array — each translation option carries its own keyWords.
             * @default []
             */
            keyWords: {
                /** @description A meaningful word or phrase exactly as it appears in the source text. */
                source: string;
                /** @description Its counterpart in this specific translation option. */
                target: string;
                /** @description Romanization of target when it is written in a non-Latin script; otherwise null. */
                romanization: string | null;
            }[];
        };
        ChatSummary: {
            id: string;
            title: string;
            sourceLang: components["schemas"]["LanguageCode"];
            targetLang: components["schemas"]["LanguageCode"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ChatTurn: {
            id: string;
            chatId: string;
            text: string;
            sourceLang: components["schemas"]["LanguageCode"];
            targetLang: components["schemas"]["LanguageCode"];
            result: components["schemas"]["TranslationResponse"];
            /** @description Index into result.translations of the chosen option. */
            selectedOption: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Parent turn id; null for a root turn. */
            parentId: string | null;
            branchIndex: number;
            branchCount: number;
            siblingIds: string[];
        };
        ChatDetail: components["schemas"]["ChatSummary"] & {
            turns: components["schemas"]["ChatTurn"][];
        };
        ApiKey: {
            id: string;
            userId: string;
            name: string;
            /** @description Leading characters of the token, for display. */
            prefix: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
        };
        CreatedApiKey: {
            apiKey: components["schemas"]["ApiKey"];
            /** @description The plaintext token, shown only once. */
            token: string;
        };
    };
    responses: {
        /** @description Error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        ProviderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    translate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                    /** @enum {string} */
                    sourceLang: "auto" | "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @enum {string} */
                    targetLang: "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @description Borrow this chat's recent turns as context; the result is not persisted. */
                    chatId?: string;
                };
            };
        };
        responses: {
            /** @description Translation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            502: components["responses"]["ProviderError"];
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's chats, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chats: components["schemas"]["ChatSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    /** @enum {string} */
                    sourceLang: "auto" | "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @enum {string} */
                    targetLang: "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                };
            };
        };
        responses: {
            /** @description The created chat. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["ChatDetail"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chat and its turns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["ChatDetail"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    action: "clear";
                } | {
                    /** @constant */
                    action: "rename";
                    title: string;
                };
            };
        };
        responses: {
            /** @description The updated chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["ChatDetail"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                    /** @enum {string} */
                    sourceLang: "auto" | "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @enum {string} */
                    targetLang: "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @description Optional precomputed TranslationResponse for this exact text, persisted without a second LLM call. */
                    result?: unknown;
                };
            };
        };
        responses: {
            /** @description The chat including the new turn. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["ChatDetail"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            502: components["responses"]["ProviderError"];
        };
    };
    updateTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
                turnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    selectedOption: number;
                } | {
                    /** @constant */
                    action: "retranslate";
                    text?: string;
                } | {
                    /** @constant */
                    action: "switchBranch";
                };
            };
        };
        responses: {
            /** @description The updated chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["ChatDetail"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            502: components["responses"]["ProviderError"];
        };
    };
    transcribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional language hint. */
                    language?: components["schemas"]["LanguageCode"];
                };
            };
        };
        responses: {
            /** @description Transcribed text. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    synthesize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                    /** @enum {string} */
                    lang: "en" | "ar" | "yue" | "zh" | "cs" | "nl" | "fi" | "fr" | "de" | "el" | "he" | "hu" | "id" | "it" | "ja" | "km" | "ko" | "mn" | "fa" | "pl" | "pt" | "ro" | "ru" | "es" | "sv" | "tl" | "th" | "uk" | "vi";
                    /** @description Provider voice id, e.g. alloy. */
                    voice?: string;
                };
            };
        };
        responses: {
            /** @description MP3 audio stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's API keys (no secrets). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["ApiKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description Optional future ISO 8601 expiry; omit or null for none. */
                    expiresAt?: string | null;
                };
            };
        };
        responses: {
            /** @description The created key and its one-time token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
